# Generated by Django 5.1.3 on 2024-11-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
